version: "3.7"

networks:
  default:
    driver: overlay
    attachable: true

services:
  web:
    image: registry.gitlab.com/mysnookerskills/app/web
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - api
  api:
    environment:
      - NODE_ENV=production
      - MYSNOOKERSKILLS_MONGODB_PASSWORD=aV9yvlvHPuES4n50GOsA
      - AWS_S3_KEY=N2bsOKciYTZU7jq7ud8aTEnkL+OZcRGLFUtzuUIz
      - AWS_S3_KEY_ID=AKIAIFGEYZTPCV6ZYSAA
      - EMAIL_PASSWORD_STEFF=INHn7RgNynZ5j1h2hmab
      - EMAIL_PASSWORD_INFO=Qom6YsE9XrZX8ruI0bUe
      - EMAIL_PASSWORD_PRIVACY=pyD5PKttFHqHfQ5Fixd5
      - EMAIL_PASSWORD_ADMIN=S6lnKqlZEkkDGUSbBeRx
      - EMAIL_PASSWORD_SUPPORT=7CLjzm9qC4U7tBxN7Sxn
      - EMAIL_PASSWORD_REGISTRATION=x0UJINMxzyTkgbMChJuq
      - EMAIL_PASSWORD_ACCOUNT=ZQRPWTLYZMCC0sIK9IxP
    image: registry.gitlab.com/mysnookerskills/app/api
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=4nmUirGoP39Qbckkilz6
      - MONGO_INITDB_DATABASE=MySnookerSkills
    volumes:
      - /root/mysnookerskills/mongodb-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - /root/mysnookerskills/mongodb:/data/db
  mongodb-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=MySnookerSkills
      - ME_CONFIG_MONGODB_AUTH_USERNAME=MySnookerSkills
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=aV9yvlvHPuES4n50GOsA
    depends_on:
      - mongodb
  ssh:
    image: corbinu/ssh-server
    ports:
      - "3018:22"
    volumes:
      - /root/.ssh/authenticated_keys:/root/.ssh/authenticated_keys:ro

