version: "3"

services:
  web:
    ports:
      - 3008:80
    image: registry.gitlab.com/mysnookerskills/app/web:develop
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - api
  api:
    ports:
      - 3007:3000
      - 9229:9229
    environment:
      - NODE_ENV=development
      - MYSNOOKERSKILLS_MONGODB_DEV_PASSWORD=57MvLdTU8Sr16QttYVoA
      - AWS_S3_KEY=N2bsOKciYTZU7jq7ud8aTEnkL+OZcRGLFUtzuUIz
      - AWS_S3_KEY_ID=AKIAIFGEYZTPCV6ZYSAA
      - EMAIL_PASSWORD_STEFF=INHn7RgNynZ5j1h2hmab
      - EMAIL_PASSWORD_INFO=Qom6YsE9XrZX8ruI0bUe
      - EMAIL_PASSWORD_PRIVACY=pyD5PKttFHqHfQ5Fixd5
      - EMAIL_PASSWORD_ADMIN=S6lnKqlZEkkDGUSbBeRx
      - EMAIL_PASSWORD_SUPPORT=7CLjzm9qC4U7tBxN7Sxn
      - EMAIL_PASSWORD_REGISTRATION=x0UJINMxzyTkgbMChJuq
      - EMAIL_PASSWORD_ACCOUNT=ZQRPWTLYZMCC0sIK9IxP
    image: registry.gitlab.com/mysnookerskills/app/api:develop
    command: node --inspect=0.0.0.0 server/server.js
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=GKY5eQkOz1jauoJtmh4e
      - MONGO_INITDB_DATABASE=MySnookerSkills
    volumes:
      - /root/mysnookerskills-dev/mongodb-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - /root/mysnookerskills-dev/mongodb:/data/db
  mongodb-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=MySnookerSkills
      - ME_CONFIG_MONGODB_AUTH_USERNAME=MySnookerSkills
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=57MvLdTU8Sr16QttYVoA
    depends_on:
      - mongodb
