version: "3.7"

services:
  web:
    image: registry.gitlab.com/mysnookerskills/app/web:test
    networks:
      - reverse-proxy_default
      - default
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - api
  api:
    environment:
      - NODE_ENV=testing
      - MYSNOOKERSKILLS_MONGODB_TEST_PASSWORD=Lxj3ekjHNKYQOw94KVmQ
      - AWS_S3_KEY=N2bsOKciYTZU7jq7ud8aTEnkL+OZcRGLFUtzuUIz
      - AWS_S3_KEY_ID=AKIAIFGEYZTPCV6ZYSAA
      - EMAIL_PASSWORD_STEFF=INHn7RgNynZ5j1h2hmab
      - EMAIL_PASSWORD_INFO=Qom6YsE9XrZX8ruI0bUe
      - EMAIL_PASSWORD_PRIVACY=pyD5PKttFHqHfQ5Fixd5
      - EMAIL_PASSWORD_ADMIN=S6lnKqlZEkkDGUSbBeRx
      - EMAIL_PASSWORD_SUPPORT=7CLjzm9qC4U7tBxN7Sxn
      - EMAIL_PASSWORD_REGISTRATION=x0UJINMxzyTkgbMChJuq
      - EMAIL_PASSWORD_ACCOUNT=ZQRPWTLYZMCC0sIK9IxP
    image: registry.gitlab.com/mysnookerskills/app/api:test
    networks:
      - reverse-proxy_default
      - default
    depends_on:
      - mongodb
  mongodb:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=cvr4kzpzmlXx8T0HfIcn
      - MONGO_INITDB_DATABASE=MySnookerSkills
    image: mongo
    networks:
      - default
    volumes:
      - /root/mysnookerskills-test/mongodb-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - /root/mysnookerskills-test/mongodb:/data/db
  mongodb-express:
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=MySnookerSkills
      - ME_CONFIG_MONGODB_AUTH_USERNAME=MySnookerSkills
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=Lxj3ekjHNKYQOw94KVmQ
    image: mongo-express
    networks:
      - default
    depends_on:
      - mongodb
  ssh:
    image: corbinu/ssh-server
    networks:
      - default
    volumes:
      - /root/.ssh/authorized_keys:/root/.ssh/authorized_keys:ro

networks:
  reverse-proxy_default:
    external: true
  default:
    internal: true
