version: "3"

networks:
  dbnet:
    external:
      name: dbnet

services:
  web:
    container_name: mysnookerskills-web-dev
    restart: unless-stopped
    ports:
      - 3008:80
    environment:
      - NODE_ENV=dev
    image: registry.gitlab.com/mysnookerskills/app/web:develop
  api:
    container_name: mysnookerskills-api-dev
    restart: unless-stopped
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - MYSNOOKERSKILLS_MONGODB_DEV_PASSWORD=57MvLdTU8Sr16QttYVoA
      - AWS_S3_KEY=N2bsOKciYTZU7jq7ud8aTEnkL+OZcRGLFUtzuUIz
      - AWS_S3_KEY_ID=AKIAIFGEYZTPCV6ZYSAA
      - EMAIL_PASSWORD_STEFF=INHn7RgNynZ5j1h2hmab
      - EMAIL_PASSWORD_INFO=Qom6YsE9XrZX8ruI0bUe
      - EMAIL_PASSWORD_PRIVACY=pyD5PKttFHqHfQ5Fixd5
      - EMAIL_PASSWORD_ADMIN=S6lnKqlZEkkDGUSbBeRx
      - EMAIL_PASSWORD_SUPPORT=7CLjzm9qC4U7tBxN7Sxn
      - EMAIL_PASSWORD_REGISTRATION=x0UJINMxzyTkgbMChJuq
      - EMAIL_PASSWORD_ACCOUNT=ZQRPWTLYZMCC0sIK9IxP
    image: registry.gitlab.com/mysnookerskills/app/api:develop
    networks:
      - dbnet
