version: '3.7'

services:
  web:
    image: registry.gitlab.com/mysnookerskills/app/web:develop
    networks:
      - reverse-proxy_default
      - default
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - mongodb
      - api
  api:
    environment:
      - NODE_ENV=development
      - MYSNOOKERSKILLS_MONGODB_DEV_PASSWORD=SECRET
      - AWS_S3_KEY=SECRET
      - AWS_S3_KEY_ID=AKIAIFGEYZTPCV6ZYSAA
      - EMAIL_PASSWORD_STEFF=SECRET
      - EMAIL_PASSWORD_INFO=SECRET
      - EMAIL_PASSWORD_PRIVACY=SECRET
      - EMAIL_PASSWORD_ADMIN=SECRET
      - EMAIL_PASSWORD_SUPPORT=SECRET
      - EMAIL_PASSWORD_REGISTRATION=SECRET
      - EMAIL_PASSWORD_ACCOUNT=SECRET
    image: registry.gitlab.com/mysnookerskills/app/api:develop
    networks:
      - reverse-proxy_default
      - default
    deploy:
      mode: replicated
      replicas: 2
    command: node --inspect=0.0.0.0 server/server.js
    depends_on:
      - mongodb
  mongodb:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=SECRET
      - MONGO_INITDB_DATABASE=MySnookerSkills
    image: mongo
    networks:
      - default
    volumes:
      - /root/mysnookerskills-dev/mongodb-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - /root/mysnookerskills-dev/mongodb:/data/db
  mongodb-express:
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=MySnookerSkills
      - ME_CONFIG_MONGODB_AUTH_USERNAME=MySnookerSkills
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=SECRET
    image: mongo-express
    networks:
      - default
    depends_on:
      - mongodb
  ssh:
    image: corbinu/ssh-server
    networks:
      - default
    volumes:
      - /root/.ssh/authorized_keys:/root/.ssh/authorized_keys:ro

networks:
  reverse-proxy_default:
    external: true
  default:
    internal: true
